### ISSUE TITLE
Cannot build for production

### ISSUE THREAD

**Issue by afeezaziz** [uploadcare/ngx-uploadcare-widget#10]
This the error that I get:

`ERROR in : Type UcWidgetComponent in /Users/afeezaziz/Projects/Motion/dashboard/node_modules/ngx-uploadcare-widget/release/ucWidget/ucWidget.component.d.ts is part of the declarations of 2 modules: UcWidgetModule in /Users/afeezaziz/Projects/Motion/dashboard/node_modules/ngx-uploadcare-widget/release/ucWidget/ucWidget.module.d.ts and AppModule in /Users/afeezaziz/Projects/Motion/dashboard/src/app/app.module.ts! Please consider moving UcWidgetComponent in /Users/afeezaziz/Projects/Motion/dashboard/node_modules/ngx-uploadcare-widget/release/ucWidget/ucWidget.component.d.ts to a higher module that imports UcWidgetModule in /Users/afeezaziz/Projects/Motion/dashboard/node_modules/ngx-uploadcare-widget/release/ucWidget/ucWidget.module.d.ts and AppModule in /Users/afeezaziz/Projects/Motion/dashboard/src/app/app.module.ts. You can also create a new NgModule that exports and includes UcWidgetComponentin /Users/afeezaziz/Projects/Motion/dashboard/node_modules/ngx-uploadcare-widget/release/ucWidget/ucWidget.component.d.ts then import that NgModule inUcWidgetModule in /Users/afeezaziz/Projects/Motion/dashboard/node_modules/ngx-uploadcare-widget/release/ucWidget/ucWidget.module.d.ts and AppModule in/Users/afeezaziz/Projects/Motion/dashboard/src/app/app.module.ts.`

By using ng serve and ng build, it is fine but this error pops up when using ng build --prod.

**Comment by ZNick1982** [comment]
Hello @afeezaziz.  
Thanks for this report. I will check this and write back to you shortly.

Kind regards.

**Comment by ZNick1982** [comment]
Hello @afeezaziz.
I did reproduce the issue. And it will be fixed on the next release.
Meanwhile to fix this error manually here is the workaround:
1. Open file `your_project/node_modules/ngx-uploadcare-widget/release/ucWidget/index.d.ts`
2. Comment the line: `export * from './ucWidget.module';`
3. Do the same with `index.js`
4. Rebuild your project with `ng build --prod`

Hope its helps.
Kind regards.

**Comment by isnyaga** [comment]
Thank you @ZNick1982, however I now get this error: ERROR in src/app/app.module.ts(4,29): error TS2305: Module '"/Users/kennedynyaga/Dropbox/@CodeScripts/BidSoko/BackEnd/node_modules/ngx-uploadcare-widget/release/index"' has no exported member 'UcWidgetModule'.

**Comment by ZNick1982** [comment]
Hello @isnyaga.
For now there is no need to use the module 'UcWidgetModule';
Use just the component: 'UcWidgetComponent'

Hope this helps.

Kind regards.

**Comment by Chethannp** [comment]
Hi @ZNick1982 Nikolay can you please check #14 issue please.
