### ISSUE TITLE
Use CommonModule instead of BrowserModule

### ISSUE THREAD

**Issue by TwunTee** [uploadcare/ngx-uploadcare-widget#12]
UcWidgetModule and UcWidgetCustomModule import BrowserModule instead of common module, only the app module should import BrowserModule, feature/library modules should import CommonModule. 

Version: 1.0.1

The error I get when I use UcWidgetModule:
`
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
`

**Comment by ekyfauzi** [comment]
I have same problem, please help T_T

**Comment by ekyfauzi** [comment]
Update:
In my case, i just import the component, not the module and everything works fine for me.

```typescript
import { UcWidgetComponent } from 'ngx-uploadcare-widget';
```
and

```typescript
@NgModule({
  imports: [...],
  declarations: [
    UcWidgetComponent
  ]
})
```
Hope it helps

**Comment by Chethannp** [comment]
Anyone found an answer to this? I am getting this error in my Ionic/angular project :(

**Comment by Chethannp** [comment]
This approach is giving me the following error. 

Error: Type UcWidgetComponent is part of the declarations of 2 modules: HomePageModule and CreatepostPageModule! Please consider moving UcWidgetComponent to a higher module that imports HomePageModule and CreatepostPageModule. You can also create a new NgModule that exports and includes UcWidgetComponent then import that NgModule in HomePageModule and CreatepostPageModule.
Error: Type UcWidgetComponent is part of the declarations of 2 modules: HomePageModule and CreatepostPageModule! Please consider moving UcWidgetComponent to a higher module that imports HomePageModule and CreatepostPageModule. You can also create a new NgModule that exports and includes UcWidgetComponent then import that NgModule in HomePageModule and CreatepostPageModule.

**Comment by Chethannp** [comment]
@ekyfauzi  - Can you please let us know how you solved it, The thing is I am using this UcWidgetComponent in 3 pages namely home, createpost and profile. It is giving me this error and I am not sure how to solve this :( can you please help!

**Comment by Chethannp** [comment]
@TwunTee  - I did that it is giving me APP_VERSION not defined (Uploadcare) error for prod build.

**Comment by Chethannp** [comment]
It is working fine on debug mode, but on prod build it is not showing any error but the app hungs. Also I am using ionic lazyloading is this causing an issue not sure :( stuck at this problem since 15 days.. Can you please help!

**Comment by ekyfauzi** [comment]
1. I do some modifications in:
https://github.com/ekyfauzi/ngx-uploadcare-widget/commit/3ee44202b3e22a83615f4c16dda775717e70ddb8

2. Create module like this:
```typescript
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { RouterModule } from "@angular/router";
import { NgbModule } from "@ng-bootstrap/ng-bootstrap";
import { UcWidgetComponent } from 'ngx-uploadcare-widget';

@NgModule({
    imports: [CommonModule, RouterModule, NgbModule.forRoot()],
    declarations: [UcWidgetComponent],
    exports: [UcWidgetComponent]
})
export class UploadcareModule {}
```

3. Import that module to wherever you want. It's works fine in my project.

Note: It's just quick fix, i hope they can solve this problem soon.

**Comment by bautrukevich** [comment]
@ekyfauzi can we close this issue?
