### ISSUE TITLE
APP_VERSION is not defined for UcWidget 

### ISSUE THREAD

**Issue by Chethannp** [uploadcare/ngx-uploadcare-widget#14]
I am using lazy loading approach in ionic 3. Tried to use your plugin named “ngx-uploadcare-widget” but it said the UCwidget is not defined and please import it into the page… after several hours of debugging I found that it had to be moved to a shared component folder and then import it individually in pages, by doing this all the errors were fixed and app was working fine on browser and on debug build. 

But when I did ionic cordova build --release --prod the app seems to be hung in the sense it was showing me blank white screen, since we cant debug prod I was left clueless on what is happening, later in one of the Ionic forms I learnt that we can add a call back function to this.navCtrl.setRoot(‘HomePage’). When I did that and generated a build I was able to see an error saying (ReferenceError APP_VERSION is not defined for Uploadcare) and now again i have no idea on what to do :(, The team at Ionic says it could be an issue with the plugin and they asked me to check in with the developer/Team of uploadcare widget(Angular 2), so I am posting this here. If here have encountered a similar issue or understands this problem request you to please help me in fixing this as I have been stuck here since a month and not sure what to do.

Ps: I did follow all the advised on #12, #13.

Also implemented the shared module concept as mentioned below

Fyi:

**//Shared Components Module**

import { NgModule } from ‘@angular/core’;
import { UcWidgetComponent } from ‘ngx-uploadcare-widget’;

@NgModule({
declarations: [UcWidgetComponent],
imports: [],
exports: [UcWidgetComponent]
})
export class ComponentsModule {}

App.module.ts file

//App 
**import { ComponentsModule } from ‘…/components/components.module’;**

@NgModule({
declarations: [
MyApp,
],
imports: [
HttpClientModule,
HttpModule,
BrowserModule,
IonicModule.forRoot(MyApp),
**ComponentsModule,**
],
bootstrap: [IonicApp],
entryComponents: [
MyApp,
],

//Home Module (home.module.ts file)

**import { ComponentsModule } from ‘…/…/components/components.module’;**

@NgModule({
declarations: [
HomePage,
],
imports: [
IonicPageModule.forChild(HomePage),
**ComponentsModule,**
],
})
export class HomePageModule {}

and did comment out // export * from './ucWidget.module'; in index.d.ts and index.js but I am still having the app_version not defined error. I am requesting you to please help!!!!!!

Many thanks in advance.

**Comment by Chethannp** [comment]
One more info.. If I am using this widget only on page it works great even on prod build but if I include it in multiple files is when the problem of **ReferenceError APP_VERSION is not defined** comes in, hope this may be a good info for the team and help me find a solution for this please!

**Comment by Chethannp** [comment]
Fyi> Debug Build works perfect

![debugmode1](https://user-images.githubusercontent.com/7566931/41229846-29c4d5d0-6d9b-11e8-89d2-9dfdbece81de.jpg)

![debugmode2](https://user-images.githubusercontent.com/7566931/41229844-299526d2-6d9b-11e8-8460-3bad7cff8308.jpg)


Production Mode > Fails 

![prdo-err1](https://user-images.githubusercontent.com/7566931/41229885-5155f6c4-6d9b-11e8-81e3-8debd83a652c.jpg)

![prod-err2](https://user-images.githubusercontent.com/7566931/41229884-50c7c5c0-6d9b-11e8-908f-71c1d0f22e57.jpg)

![prod-err3](https://user-images.githubusercontent.com/7566931/41229882-509808f8-6d9b-11e8-945a-6c28b0374904.jpg)

**Comment by Chethannp** [comment]
Angular CLI: 6.0.8
Node: 8.9.4
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-optimizer   0.0.35
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              5.5.11
typescript                        2.6.2
webpack                           3.8.1

I think the issue is with this line from ucWidget.component.js ---> 
**uploadcare.start({ integration: "Angular/" + VERSION.full + "; Ngx-Uploadcare-Widget/" + APP_VERSION });** 

I think i have given the information  to the fullest, please help :(

**Comment by TwunTee** [comment]
I did a quick search and from what i can see https://github.com/uploadcare/ngx-uploadcare-widget/blob/07cfa99efbef72eb94d7108a5e1f973d04731742/src/ucWidget/ucWidget.component.ts#L12 is that APP_VERSION should have be getting a injected value from here https://github.com/uploadcare/ngx-uploadcare-widget/blob/95a275a11ec08791d78eeafc16440fea720551d9/config/webpack.common.js#L78 but I think it is not getting injected properly, i haven't tried a product build will let you know if i get the same issue

**Comment by Chethannp** [comment]
@Zmoki - any update on this please???

**Comment by ZNick1982** [comment]
Hi, 
I just fixed the initialization of `APP_VERSION`:
https://github.com/uploadcare/ngx-uploadcare-widget/tree/APP_VERSION_Fix
 Unfortunately I have no possibility check this with IONIC.
Can you test it please, If its works. I will create PR

**Comment by Chethannp** [comment]
Sorry ignore the above message i figured it out and will test it and let you know!

**Comment by Chethannp** [comment]
@ZNick1982 - I think this issue is fixed. I am not able to see an errors and it is working fine. In case if there are any issues I will report here. Thank you for the support!

**Comment by Chethannp** [comment]
Also does this thing fix the AOT build error as well? #10

**Comment by ZNick1982** [comment]
Yes it's should resolve #10 also.

**Comment by Chethannp** [comment]
Thank you so much @ZNick1982 for your help. I would also request you to please advice me on issue #16  I had mailed all the details to Alex at uploadcare but he asked me to create an issue here. Requesting you to please check this once.

Thanks a million your efforts!!!!
