### ISSUE TITLE
Uploadcare widget facebook/dropdobox/..etc authentication opens in a browser and not inside the app 

### ISSUE THREAD

**Issue by Chethannp** [uploadcare/ngx-uploadcare-widget#16]
I have an issue here… All I am doing is using ngx-uploadcare-widget in my app. This widget allows to share and upload photos from different platforms like facebook, twitter, instagram, dropbox and so on.
The moment I click on any of these say for example I click on connect via facebook it opens up a mobile browser and after I click on allow it doesnot redirect to the app, so I thought I should open it in the in app browser so that it opens up in the app. But not sure on how to watch on external links because the moment I click on the upload an image via uploadcare button inside the app it opens up a widget which I do not have access to. All I want to do is to learn a method on opening all the external links clicked on the ionic app to open it in InappBrowser and not on mobile browser. I have posted this in the Ionic Forum as well..

Please see if the widget can consider checking the inappbrowser at first. Reuqesting your help because this is the core feature of using this widget.

Thanks in advance.

**Comment by Chethannp** [comment]
![2018_06_19_19_04_21_window](https://user-images.githubusercontent.com/7566931/41600475-a250b9ca-73f3-11e8-8ac3-709b16d3ba55.png)
At this stage when I click on facebook/dropbox/Instagram/Drive/google photos it opens up a new window and its perfectly a normal behavior on web but on mobile app it opens up a new browser window outside the app and hence after authentication the browser just stays like that and does not return back to the app.

**Comment by ZNick1982** [comment]
@Zmoki Hi, could you please assist? 
I am not sure that regards Angular component.

**Comment by Chethannp** [comment]
I did open this issue on Ionic Forum (https://forum.ionicframework.com/t/uploadcare-widget-facebook-authentication-opens-in-a-browser-and-not-inside-the-app/133063) as well and it is left unnoticed, The primary goal of using this widget in an hybrid app was to allow user to gain access to his personal drives but now the entire widget is helping me in just uploading local files :( and I am very badly stuck, @Zmoki  requesting you to please help me figure out a way to do this!! Thanks a ton in advance!

**Comment by Chethannp** [comment]
My Debugging so far: 

![directive-approach](https://user-images.githubusercontent.com/7566931/41645144-b84bf506-748d-11e8-9187-78049f5d2076.png)

Created a host listener directive for listening on  clicks that happen on the widget. I am able to catch hold of the clicks just before this above screen and redirecting it to open it in in app browser.

Below Is my sample code: Nothing.ts for listening on clicks for this purpose I am using Ionic Theme able browser (https://ionicframework.com/docs/native/themeable-browser/).

**home.html**
<ngx-uploadcare-widget **nothing**
    images-only="true"
    public-key="YOUR_PUBLIC_KEY">
  </ngx-uploadcare-widget>

**Nothing.ts**
@Directive({
  selector: '[nothing]', // Attribute selector
  host: {
    '(window:click)' : 'doSomething($event)'
  }
})

doSomething(eve){

    if(event.target && eve.target.href){
      eve.preventDefault();
      this.openBrowser(eve.target.href);
    } 

  }

and then in the constructor.

  openBrowser(href){
    const options: ThemeableBrowserOptions = {
            statusbar: {
                color: '#ffffffff'
            },
            toolbar: {
                height: 44,
                color: '#f26722ff'
            },
            title: {
                color: '#003264ff',
                showPageTitle: true
            },
            closeButton: {
              wwwImage: 'assets/imgs/close-icon.png',
              align: 'right',
              event: 'closePressed'
            },
            backButtonCanClose: true 
       };

    let target = "_self";
    this.iab.create(href,target,options); 
  }

but from this screen I am unable to catch hold of any clicks it straight away asks for browser options on phone :( (pic below as shown) 

![screenshot_20180620-133208](https://user-images.githubusercontent.com/7566931/41645593-0c744042-748f-11e8-99b2-d4c83cee5cb5.jpg)

This is my first project on building an hybrid app and this widget is giving me a ride of a life time :D 

Thanks!

**Comment by Chethannp** [comment]
![capture](https://user-images.githubusercontent.com/7566931/41648372-5067a9d6-7496-11e8-8206-c61ce2dbe197.png)
I am able to capture at this level of click but beyond this is an iframe and it is not letting me capture any clicks and it directly open the browser outside the app :( 

@Zmoki - I am requesting you to please help me !!!!!

**Comment by Zmoki** [comment]
@Chethannp thanks for the details! I need some time to look into it. I'll get back to you on this as soon as possible.

**Comment by Chethannp** [comment]
@zomki - Can you please provide an update on this.

**Comment by Zmoki** [comment]
@Chethannp sorry for the delay. I don't know much about mobile development. As far as I understood during my research, browser's OAuth2 authentification in ionic apps is a common problem. Maybe this [solution for Cordova](https://kb.uploadcare.com/article/142-basic-cordova-setup) (but with [`@ionic-native/in-app-browser`](https://www.npmjs.com/package/@ionic-native/in-app-browser)) is also suitable for Ionic?

Also, we have widget native versions for both [android](https://github.com/uploadcare/uploadcare-android) and [iOS](https://github.com/uploadcare/uploadcare-ios).

**Comment by Chethannp** [comment]
Checking it.

**Comment by Chethannp** [comment]
I think I have tried all possible things to catch hold of the click but it does not work at all.... Tried the below code to capture the iframe click inside the app. 

```
        window.focus(); //force focus on the currenct window;
        window.addEventListener('blur', function(e){
            if(document.activeElement.tagName == "IFRAME")
            {
              e.preventDefault();
                alert('Focus Left Current Window and Moved to Iframe / Possible click!');
            }
        });
```
I was able to catch the click but to get the url from the iframe it is throwing me a CORS error :( 
Uncaught DOMException: Blocked a frame with origin "http://192.168.1.2:8100" from accessing a cross-origin frame.
    at eval (eval at <anonymous> (http://192.168.1.2:8100/build/main.js:977:27), <anonymous>:1:20)
    at http://192.168.1.2:8100/build/main.js:977:27

OMG I am not sure on how to work with this.

**Comment by Chethannp** [comment]
@Zmoki - I was able to resolve the inappbrowser thing by making changes to my ionic config.xml file by adding the below command.

**<allow-navigation href="*" />**

Now the auth opens inside the app but it doesn't auto close and return to the widget, it simply shows a message saying Authentication complete -> Close this page to continue. now when I press the device back button it takes me back to the home page rather than the widget. Again this time if I open uploadcare and select facebook, It shows my name and a logout option but it doesn't show me any images from facebook. Please find the screenshot below. 

![screenshot_20180704-191013](https://user-images.githubusercontent.com/7566931/42280526-9e78f610-7fbe-11e8-856f-05b5e900b4b6.jpg)

Our app is built in such a way that it uses the Uploadcare service to a maximum extent. Its a humble request to you and your team to please help us figure out a way in getting this issue resolved asap.

In fact I can send you a sample apk / code for you to reproduce it on your phone, please let me know if you want me to do this I can create a new project on ionic and share a link here.

My Sincere request!

**Comment by Zmoki** [comment]
@Chethannp 

Unfortunately, I think there is no way to fix this and use the JS web version of the widget in hybrid applications, especially if you want to use social tabs, say, Google [has blocked](https://developers.google.com/identity/protocols/OAuth2InstalledApp) the web OAuth authorization and recommended to use native solutions instead.

See [this article](https://medium.com/@jlchereau/stop-using-inappbrowser-for-your-cordova-phonegap-oauth-flow-a806b61a2dc5) to learn more.

I strongly advise you to use native versions of the widget for [android] and [iOS].

[android]: https://github.com/uploadcare/uploadcare-android
[iOS]: https://github.com/uploadcare/uploadcare-ios

**Comment by Chethannp** [comment]
@Zmoki - I think we have reached a dead end :( will drop this widget for now. Requesting you to please update when the Uploadcare team has an working solution specific to hybrid applications like Ionic / React.

Thanks again for your valuable time!

**Comment by optlsnd** [comment]
@Chethannp 

We just noticed the Facebook tab issue is not related to using the hybrid app. Something went wrong with our Facebook app's permissions and we're fixing it now. I'll keep you updated.

**Comment by Chethannp** [comment]
![aot-error](https://user-images.githubusercontent.com/7566931/42406845-a2e3f27a-81cd-11e8-97a6-6b49897f1bee.png)

This AOT error still exists!

**Comment by Chethannp** [comment]
Any update on this ??? also can you please check #17
