### ISSUE TITLE
Issue while taking Angular build 

### ISSUE THREAD

**Issue by Nandhan-augment** [uploadcare/ngx-uploadcare-widget#19]
Hi, Since release/ucWidget/ucWidget.component.d.ts doesn't have a validator member in the UcWidgetComponent class. Validator is not working while taking an angular build.

**Comment by ZNick1982** [comment]
Hello @Nandhan-augment.  Thanks to the issue.
I will fix and update release shortly.

**Comment by Nandhan-augment** [comment]
Okay

**Comment by ZNick1982** [comment]
Hi @Nandhan-augment 
Issue is fixed with v 1.1.1

**Comment by Nandhan-augment** [comment]
Thanks @ZNick1982

**Comment by Nandhan-augment** [comment]
Hi
Now importing UgWidgetComponent is having a problem. It’s getting a message like the component is already imported in ngx-upload-care node module (one if the file). How can we import it here then ?

**Comment by ZNick1982** [comment]
Hi @Nandhan-augment .
First, you need to to import module:
`import { UcWidgetModule } from 'ngx-uploadcare-widget';`
and add this to your module as in example:
```
@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp),
    UcWidgetModule
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}
```
Just use the component in the your app:
```
<ion-header>
  <ion-navbar>
    <ion-title>
      About
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
  <ngx-uploadcare-widget>
  </ngx-uploadcare-widget>

</ion-content>
```
Hope this helps.

**Comment by bautrukevich** [comment]
@Nandhan-augment do you tried? can we close this issue?

**Comment by bautrukevich** [comment]
@Nandhan-augment thanks!
