### ISSUE TITLE
Angular widget reject issue

### ISSUE THREAD

**Issue by Nandhan-augment** [uploadcare/ngx-uploadcare-widget#28]
As per our request you have implemented reject option for angular widget. The above functionality works well on development environment, but after taking an angular build the reject is not working.

**Comment by ZNick1982** [comment]
Hello @Nandhan-augment .
Thanks for reporting this.

I will check and reply to you shortly.

Best regards.

**Comment by ZNick1982** [comment]
Hello @Nandhan-augment  I checked the reject twice and its work for me fine.
Can you send me the example of usage where error occurs?

Kind regards,
Nikolay Zherdev.

**Comment by Nandhan-augment** [comment]
Hi,

Could you sent your sample code for reference? For me the issue was occuring after taking angular build.

Thanks Nandha

**Comment by Nandhan-augment** [comment]
Okay, thanks
