### ISSUE TITLE
Error while using binding property

### ISSUE THREAD

**Issue by amanrathie** [uploadcare/ngx-uploadcare-widget#32]
Hi,

I'm trying the upload widget for Angular in a new project that we are
starting. Everything is working fine, but when I try to use any binding
property, for example: [publicKey] I get this message:

*core.js:15723 ERROR Error: Uncaught (in promise): Error: Template parse
errors:*
*Can't bind to 'publicKey' since it isn't a known property of
'ngx-uploadcare-widget'.*
*1. If 'ngx-uploadcare-widget' is an Angular component and it has
'publicKey' input, then verify that it is part of this module.*
*2. If 'ngx-uploadcare-widget' is a Web Component then add
'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to
suppress this message.*
*3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas'
of this component. ("*
* <div class="col-sm-12">*
* <ngx-uploadcare-widget*
* [ERROR ->][publicKey]="ngxUploadPublicKey"*
* data-tabs="file url"*

If I use the publicKey value directly without the binding it works fine.
I'm using angular 7 with this version:

"ngx-uploadcare-widget": "^1.2.3"

Any help would be appreciated.

Thanks!

**Comment by bautrukevich** [comment]
@amanrathie Thank you for the issue.

@ZNick1982 can you help?

**Comment by ZNick1982** [comment]
Hello @amanrathie .

Please checkout the demo repo: https://github.com/ZNick1982/ngx-uploadcare-widget-demo
You can find how to define the key in [app.component.ts](https://github.com/ZNick1982/ngx-uploadcare-widget-demo/blob/8fd19a4c446778355cb82fbb6931dd8e7cb049a0/src/app/app.component.ts#L13). 

Kind regards,
Nikolay Zherdev

**Comment by amanrathie** [comment]
Thanks, that's was helpful.

Em seg, 25 de mar de 2019 às 08:54, Nikolay <notifications@github.com>
escreveu:
