### ISSUE TITLE
Angular 8 compatibility

### ISSUE THREAD

**Issue by mwawrusch** [uploadcare/ngx-uploadcare-widget#33]
Trying to upgrade to angular 8 but getting the following errors:

```
Package "ngx-uploadcare-widget" has an incompatible peer dependency to "@angular/core" (requires "5.x" (extended), would install "8.0.0").
                  Package "ngx-uploadcare-widget" has an incompatible peer dependency to "@angular/animations" (requires "5.x" (extended), would install "8.0.0").
                  Package "ngx-uploadcare-widget" has an incompatible peer dependency to "@angular/platform-browser" (requires "5.x" (extended), would install "8.0.0").
                  Package "ngx-uploadcare-widget" has an incompatible peer dependency to "@angular/common" (requires "5.x" (extended), would install "8.0.0").
                  Package "ngx-uploadcare-widget" has an incompatible peer dependency to "rxjs" (requires "5.x", would install "6.5.2").
```

**Comment by ZNick1982** [comment]
Hi @mwawrusch .
Thanks for reporting this.
I will check and write back to you shortly.

Kind regards,
Nikolay Zherdev.

**Comment by ZNick1982** [comment]
Hi @mwawrusch .
I checked on Angular 8 it works fine.
And also updated the example demo to Angular 8.0
You can find this demo here: https://github.com/ZNick1982/ngx-uploadcare-widget-demo.git

Meanwhile we will add compatibility of Angular 8.x to the widget and release it in the next version.

Kind regards,
Nikolay Zherdev.

**Comment by mwawrusch** [comment]
Thx. Much appreciated

**Comment by wilfredonoyola** [comment]
Hi @mwawrusch @ZNick1982 , Does this work with Angular 8 for last versionngx-uploadcare-widget? Let me know

Thanks

**Comment by ZNick1982** [comment]
Yes it works on Angular 8
