### ISSUE TITLE
Angular universal support

### ISSUE THREAD

**Issue by olehleskiv** [uploadcare/ngx-uploadcare-widget#35]
I have issue with serving the application using SSR.

```
"@angular/core": "~8.0.1",
 "@nguniversal/express-engine": "^8.1.1",
 "@nguniversal/module-map-ngfactory-loader": "8.1.1",
```

Steps to reproduce
1. Add universal support to existing project
`ng add @nguniversal/express-engine --clientProject {ptojectName}`
2. Add `ngx-uploadcare-widget` widget and use in project
3. Run `npm run build:ssr && npm run serve:ssr`

Got an error
```> node dist/server

/projects/my-project/dist/server/main.js:173497
uploadcare_widget__WEBPACK_IMPORTED_MODULE_1___default.a.start({ integration: "Angular/" + _angular_core__WEBPACK_IMPORTED_MODULE_0__[/* VERSION */ "lb"].full + "; Ngx-Uploadcare-Widget/" + APP_VERSION });
                                                         ^

TypeError: uploadcare_widget__WEBPACK_IMPORTED_MODULE_1___default.a.start is not a function
    at Object.p0HS (/projects/my-project/dist/server/main.js:173497:58)
    at __webpack_require__ (/projects/my-project/dist/server/main.js:26:30)
   .....
```

**Comment by ZNick1982** [comment]
Hi @olehleskiv.
I will take a look and write back to you shortly.

**Comment by ZNick1982** [comment]
Hi @olehleskiv 
I was able to reproduce the error.
Currently working on it.

**Comment by ZNick1982** [comment]
Fixed in https://github.com/uploadcare/ngx-uploadcare-widget/pull/36 As soon as PR pass code review new version will be released.
