### ISSUE TITLE
angular 9 issue with ivy

### ISSUE THREAD

**Issue by yaacov1974** [uploadcare/ngx-uploadcare-widget#43]
hello
im getting this error -

ERROR in node_modules/ngx-uploadcare-widget/release/ucWidget/ucWidget.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of SettingModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-uploadcare-widget) which declares UcWidgetModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class UcWidgetModule {
                       ~~~~~~~~~~~~~~
node_modules/ngx-uploadcare-widget/release/ucWidget/ucWidget.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of ContactModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-uploadcare-widget) which declares UcWidgetModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class UcWidgetModule {

**Comment by nd0ut** [comment]
Hello! Can you tell me which version you're using?
Version `2.x` should work with Ivy. Please check https://github.com/uploadcare/ngx-uploadcare-widget/issues/37

**Comment by yaacov1974** [comment]
hi , i did npm install uploadcare-widget

‫בתאריך יום ד׳, 29 באפר׳ 2020 ב-14:55 מאת ‪Aleksandr Grenishin‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by yaacov1974** [comment]
now i see im on v3 ... how can i change it to v2 ?

‫בתאריך יום ד׳, 29 באפר׳ 2020 ב-15:07 מאת ‪yaacov zur‬‏ <‪
yaacov.zur@gmail.com‬‏>:‬

**Comment by nd0ut** [comment]
You need to install `ngx-uploadcare-widget`, not `uploadcare-widget`

**Comment by yaacov1974** [comment]
great , thanks

‫בתאריך יום ד׳, 29 באפר׳ 2020 ב-15:31 מאת ‪Aleksandr Grenishin‬‏ <‪
notifications@github.com‬‏>:‬
