### ISSUE TITLE
Angular 10 upgrade fails.

### ISSUE THREAD

**Issue by mwawrusch** [uploadcare/ngx-uploadcare-widget#51]
### Describe the bug

Angular 10 upgrade fails.

Upgrade to angular 10, then launch. You will receive the following error message:

ERROR in The target entry-point "ngx-uploadcare-widget" has missing dependencies:
 - uploadcare-widget

### Expected behavior

Not to fail

### Environment

 - Library version:    "ngx-uploadcare-widget": "2.0.2",
 - Language/framework version: Angulra 10
 - OS version: Mac

**Comment by gopal-augment** [comment]
Try to to install its peer dependency "uploadcare-widget": "^3.10.2".

**Comment by mwawrusch** [comment]
Haha, ok totally missed that. Maybe I need to start drinking coffee again. Thx, much appreciate the quick help.

**Comment by rsedykh** [comment]
@mwawrusch we've updated the repo's readme to remind installing this dependency. :-)

**Comment by jonmbennett** [comment]
The peer dependency is not mentioned here: https://uploadcare.com/docs/integrations/angular/

That might cause some people to experience this. Such as myself, today. :)
