### ISSUE TITLE
Controlling the widget: 1) Resetting it; 2) getting current files independent from events

### ISSUE THREAD

**Issue by cmauersberger** [uploadcare/ngx-uploadcare-widget#6]
I am not sure whether this is an "issue" for ngx-uploadcare-widget, or a rather angular specific question, but in my view it must be a very common scenario for the use of the widget in forms.

**The scenario:** 
The uploadcare widget is part of a form, where users provide input and use the widget to upload images. Once they press "Save" on my form, form data gets to the backend, including the Uuid of the uploaded files/group. There, the uploaded images get marked as "stored" and other data-processing is done. The user remains on the form page with the widget, seeing (hopefully) a message "Successfully saved". Here come my **questions**:

1) When the saving is done in my backend, **I want the widget to be cleared**. The files are now stored and shown to the user as part of the form, so I don't want them in the widget anymore. How to do? (Without this, I can't really use the widget for my forms...)

2) When my user saves my form, I want to transmit the Uuids currently in the widget. How can I **access this file information when I want** (when the user clicks on "Save" in my form), independent from events fired by the widget. (Workaround is to listen to the onChange event and store current uuid in local variable that only gets used when user presses "save").

3) (addon) I want to disable the "Save" button on my form, as long as images are being uploaded. **How can I check if any uploads are still being processed?**

Any hints and answers are highly appreciated!

**Comment by ZNick1982** [comment]
Hi Christof.
Thanks for this questions. Good points for component improvements. :)
* For point 1, this is under development right now. Hope it's will be released on the next week.
* For point 2 yes you're right, the `on-change` event can be used.  The input parameters for this event could be different and depends on `multiple` attribute. If attribute is set to true, then widget allows to upload multiple files simultaneously. In this case input parameter of `on-change` handler contains set of promises for files. Here is an example:
```html
      <ngx-uploadcare-widget
        images-only="true"
        public-key="demopublickey"
        multiple="true"
        (on-upload-complete)="onUpload($event)"
        (on-change)="onChange($event)">
      </ngx-uploadcare-widget>
```
```javascript
  onChange(info) {
    console.log('fired Event "onChange"');
//  info contains 2 methods:
//  .promise() - returns the general promise for all uploading files which resolves with the group info of uploaded files
//  .files() - returns the array of promises for each uploading file. Each promise resolves with uploaded file info
    info.promise().then((groupInfo) => {
      console.log('resolved general promise from "onChange" with data:');
      console.log(groupInfo);
    });
    info.files().forEach((promise) => {
      promise.then((fileInfo) => {
        console.log('resolves file promise with file info:');
        console.log(fileInfo);
      });
    });
  }
```
If `multiple` is not set then widget allows to upload only 1 file and `on-change` event will be fired with  file promise right after widget closed.
More info about this event you can find [here](https://uploadcare.com/docs/api_reference/javascript/widget/#widget-on-change)
* For point 3, I think you can also use `on-change` event, for example, disable Save button until the general or file promise will be resolved.

Hope this helps.

**Comment by ZNick1982** [comment]
Hi Christof.
New version of component just released. Its interactive and contains methods for widget reset and clear uploads.

Kind Regards,
Nikolay.

**Comment by cmauersberger** [comment]
Works perfect, thank you!
