### ISSUE TITLE
how to reset uploadcare widget to original state after the file upload is complete in angular

### ISSUE THREAD

**Issue by AhmedSaladin** [uploadcare/ngx-uploadcare-widget#66]
how to reset upload care widget to original state after the file upload is complete in angular I have tried to handle it with CSS and it wouldn't work.

**Comment by optlsnd** [comment]
Hi @AhmedSaladin, you can use either the `clearUploads` or `reset` method to reset the widget's state. Both methods are accessible from a parent component via the `@ViewChild()` approach. See [Methods](https://github.com/uploadcare/ngx-uploadcare-widget#methods) and this [demo app](https://github.com/uploadcare/ngx-uploadcare-widget/blob/master/projects/demo/src/app/app.component.ts) for more details.

**Comment by AhmedSaladin** [comment]
@optlsnd  thanks I'm gonna check the demo app
