### ISSUE TITLE
Component vs. Directive

### ISSUE THREAD

**Issue by MatthiasKunnen** [uploadcare/ngx-uploadcare-widget#8]
Why is this not an attribute directive? This would allow for easier custom styling and changes to the button text.

**Comment by ZNick1982** [comment]
Hello Matthias.
The Directive will be released in future. For now the component uses its markup and styles out from the box.

**Comment by MatthiasKunnen** [comment]
Would it be possible to give an estimated completion date or a milestone/issue I could watch in order to stay up-to-date about this future release?

**Comment by ZNick1982** [comment]
Hello Matthias.
Planned version with directive is estimated to the middle of April.
I will write you in this issue when its ready.

Kind regards,
Nikolay.

**Comment by MatthiasKunnen** [comment]
Thank you in advance, should I close this issue in the meanwhile?
