### ISSUE TITLE
Documention may be slightly outdated in typescript

### ISSUE THREAD

**Issue by peternixey** [uploadcare/ngx-uploadcare-widget#93]
### Describe the bug

Having just installed the UC widget into a new project I noticed that it was throwing some errors in both VSCode and also during compilation. These were coming because the documentation suggests that attributes should be passed to the UC widget as strings where a number of them are not string types and so need to be passed using square brackets around attribute names.

### Expected behavior

The documentation should provide code snippets that work in contemporary Angular and typescript. 

### Code / screenshots

**Doesn't work**

```ts
<ngx-uploadcare-widget public-key="KEY"
                        images-only="true">
</ngx-uploadcare-widget>
```
![image](https://user-images.githubusercontent.com/168592/156569132-6dcd3e9e-2736-4871-8aba-217d032ec84f.png)

Error: `Type 'string' is not assignable to type 'boolean'.ngtsc(2322)`

**Does work**

```ts
<ngx-uploadcare-widget public-key="KEY"
                        [images-only]="true">
</ngx-uploadcare-widget>
```

The same is true of other attributes that do not have type string:

**Doesn't work**

```ts
<ngx-uploadcare-widget public-key="KEY"
                        clearable="true">
</ngx-uploadcare-widget>
```
![image](https://user-images.githubusercontent.com/168592/156569093-257bdd03-5600-4274-874b-9c36919296cb.png)

Error: `Type 'string' is not assignable to type 'boolean'.ngtsc(2322)`

**Does work**

```ts
<ngx-uploadcare-widget public-key="KEY"
                        [clearable]="true">
</ngx-uploadcare-widget>
```

### Environment

 - Library version: 3.0.2
 - Language/framework version: Angular 13.2.0, Typescript: 4.5.2

**Comment by nd0ut** [comment]
Hey @peternixey,

thank you! We're fixed it.
